spring.application.name=demo

###############################################
# Database
###############################################

spring.datasource.url=jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:demo_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.connection-init-sql=SET SESSION innodb_lock_wait_timeout = 90


###############################################
# JWT / Security
###############################################

jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
jwt.issuer=${JWT_ISSUER:demo-banking-api}
jwt.audience=${JWT_AUDIENCE:demo-banking-client}

auth.mode=${AUTH_MODE:jwt}
auth.pre-auth-key=${PRE_AUTH_KEY:}


###############################################
# Kafka
###############################################

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.missing-topics-fatal=false

transaction.notification.topic=${KAFKA_NOTIFICATION_TOPIC:transaction-notifications}
transaction.notification.group-id=${KAFKA_NOTIFICATION_GROUP:transaction-email-notification}


###############################################
# Actuator
###############################################

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never


###############################################
# Email
###############################################

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


###############################################
# Daily Audit Scheduler
###############################################

app.audit.daily.cron=${AUDIT_CRON:0 0 0 * * *}

audit.admin.email=${AUDIT_ADMIN_EMAIL}
audit.mail.from=${AUDIT_MAIL_FROM}


###############################################
# Redis
###############################################

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}